version: '3.7'

services:
  php-fpm:
    container_name: generic-request
    build:
      context: ./.docker/php
      args:
        WITH_XDEBUG: $WITH_XDEBUG
        GITHUB_TOKEN: $GITHUB_TOKEN
        USER_ID: $USER_ID
    env_file: .env
    volumes:
      - .:/var/www/html:delegated
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
